name: Build and Test App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Setup Nuget
      uses: Nuget/setup-nuget@v1.0.5
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Remove ref
      run: dotnet remove ./SmartRoom.Tests/SmartRoom.Tests.csproj reference ./SmartRoom/SmartRoom.csproj
      
    - name: Install dependencies
      run: nuget restore ./SmartRoom.sln
      
    - name: Install NUnit.ConsoleRunner
      run: nuget install NUnit.ConsoleRunner
      
    - name: Add ref
      run: dotnet add ./SmartRoom.Tests/SmartRoom.Tests.csproj reference ./SmartRoom/SmartRoom.csproj
      
    - name: Build
      run: msbuild ./SmartRoom.sln /p:Configuration=Debug
      
    - name: Test
      run: ./NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe ./SmartRoom.Tests/bin/Debug/SmartRoom.Tests.dll
